backend:
  name: github
  repo: emma-g-123/cabot
  branch: main
  site_domain: eclectic-buttercream-4391c7.netlify.app

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog Posts"
    folder: "_content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}